# -*- coding: utf-8 -*-
"""kasir_mandiri

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Ev4uTIy4Vy0r7l8coRyZcrYGCmF-2kJn
"""

"""
Import Modul pandas untuk membantu visualisasi
tabel pada method check_order
"""
import pandas as pd

class Transaction:
  def __init__(self):
    self.data_belanjaan = dict()


  
    """
    Fungsi untuk menambahkan data belanjaan

    parameters
    nama   : str   nama items
    jumlah : int   jumlah items
    harga  : int   harga per items
    """
  def add_item(self, nama, jumlah, harga):
    self.data_belanjaan.update({nama: [jumlah, harga, jumlah * harga]})

  def update_item_name(self, nama, nama_baru):
    temp = self.data_belanjaan[nama] # membuat variabel sederhana
    self.data_belanjaan.pop(nama)
    self.data_belanjaan.update({nama_baru: temp})
  
  def update_item_qty(self, nama, jumlah_baru):
    self.data_belanjaan[nama][0] = jumlah_baru
    self.data_belanjaan[nama][2] = jumlah_baru * self.data_belanjaan[nama][1]

  def update_item_price(self, nama, harga_baru):
    self.data_belanjaan[nama][1] = harga_baru
    self.data_belanjaan[nama][2] = harga_baru * self.data_belanjaan[nama][0]

  
  def delete_item(self,nama):
    self.nama = nama
    if nama == nama:
      self.data_belanjaan.pop(nama)
  
  def reset_transaction(self):
    self.data_belanjaan.clear()
    print("Semua item berhasil di delete!")
  

  def check_order(self):
    if(len(self.data_belanjaan) == 0):
        print("Terdapat Kesalahan Input Data!")
    else:
        data = pd.DataFrame(self.data_belanjaan).T
        data.columns = [ "Jumlah item", "Harga per item", "Total Harga"]
        data["Total Harga"] = data["Jumlah item"] * data["Harga per item"]
        print(data.to_markdown())

  
  def total_price(self):
    total = 0
    for i in self.data_belanjaan.values():
      total += i[2]

    
    if total > 500000:
      total *= 0.9
    elif total > 300000:
      total *= 0.92
    elif total > 200000:
      total *= 0.95

    return f"Total belanja yang harus dibayarkan adalah Rp. {format(total, ',')}"