# -*- coding: utf-8 -*-
"""main.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1OME6yx3_52US_XGADfACU-XwKkVt1lG-
"""

import pandas as pd

import kasir_mandiri

from kasir_mandiri import Transaction

transaction_123 = Transaction()

transaction_123.add_item("Ayam Goreng", 2, 20_000)

transaction_123.add_item("Pasta Gigi", 3, 15_000)

transaction_123.check_order()

transaction_123.delete_item("Pasta Gigi")

transaction_123.check_order()

transaction_123.reset_transaction()

transaction_123.add_item("Ayam Goreng", 2, 20_000)

transaction_123.add_item("Pasta Gigi", 3, 15_000)

transaction_123.add_item("Mainan Mobil", 1, 200_000)

transaction_123.add_item("Mie Instant", 5, 3_000)

transaction_123.check_order()

transaction_123.total_price()